export const HANDOFF_CONFIG = {
  TTL_SECONDS: 10 * 60,

  OTP_TTL_SECONDS: 5 * 60,

  MAX_OTP_ATTEMPTS: 5,

  CREATE_LIMIT: 10,

  CREATE_WINDOW_SECONDS: 60,

  READ_LIMIT: 30,

  READ_WINDOW_SECONDS: 60,

  OTP_VERIFY_LIMIT: 5,

  OTP_VERIFY_WINDOW_SECONDS: 5 * 60,

  OTP_RESEND_LIMIT: 3,

  OTP_RESEND_WINDOW_SECONDS: 10 * 60,
};